// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcOBEC1HdPBaOtoz9wQztkKflGebBaQ0Y',
    appId: '1:444872585677:web:4eb716504d1137d1cd9484',
    messagingSenderId: '444872585677',
    projectId: 'fotocompra-gpt',
    authDomain: 'fotocompra-gpt.firebaseapp.com',
    storageBucket: 'fotocompra-gpt.firebasestorage.app',
    measurementId: 'G-QH7Y5TP830',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJPFhX4WkIiMxh3yaL_xLlfQKYv6EocU',
    appId: '1:444872585677:android:e1fd139e30997103cd9484',
    messagingSenderId: '444872585677',
    projectId: 'fotocompra-gpt',
    storageBucket: 'fotocompra-gpt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdRQwzDpd4FoBKExNROXXw3nMQj7-1TzU',
    appId: '1:444872585677:ios:2b8b28d97fa4641acd9484',
    messagingSenderId: '444872585677',
    projectId: 'fotocompra-gpt',
    storageBucket: 'fotocompra-gpt.firebasestorage.app',
    iosClientId: '444872585677-hsvf18gduglre2k7ok0ka7ove95a7kp0.apps.googleusercontent.com',
    iosBundleId: 'com.barrasa.fotolistaGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdRQwzDpd4FoBKExNROXXw3nMQj7-1TzU',
    appId: '1:444872585677:ios:2b8b28d97fa4641acd9484',
    messagingSenderId: '444872585677',
    projectId: 'fotocompra-gpt',
    storageBucket: 'fotocompra-gpt.firebasestorage.app',
    iosClientId: '444872585677-hsvf18gduglre2k7ok0ka7ove95a7kp0.apps.googleusercontent.com',
    iosBundleId: 'com.barrasa.fotolistaGpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcOBEC1HdPBaOtoz9wQztkKflGebBaQ0Y',
    appId: '1:444872585677:web:77e9c414b60faea2cd9484',
    messagingSenderId: '444872585677',
    projectId: 'fotocompra-gpt',
    authDomain: 'fotocompra-gpt.firebaseapp.com',
    storageBucket: 'fotocompra-gpt.firebasestorage.app',
    measurementId: 'G-8NY17WFGJ8',
  );
}
